

spring:
  h2:           # H2 console 설정
    console:
      enabled: true
      path: /h2-console
  datasource:   # H2 데이터 베이스 설정
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/testdb
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none